In [1]:
import pandas as pd

df = pd.read_csv("/home/hvgupta/COMP4222/COMP4222_F25-26/src/one_year_company_info.csv")

In [2]:
df.isnull().sum()

Date      0
Symbol    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [3]:
len(df["Symbol"].unique())

182

In [14]:
df.columns

Index(['Exchange', 'Symbol', 'Shortname', 'Longname', 'Sector', 'Industry',
       'Currentprice', 'Marketcap', 'Ebitda', 'Revenuegrowth', 'City', 'State',
       'Country', 'Fulltimeemployees', 'Longbusinesssummary', 'Weight'],
      dtype='object')

In [15]:
df["Weight"]

0      0.069209
1      0.059350
2      0.058401
3      0.042550
4      0.042309
         ...
497    0.000125
498    0.000125
499    0.000120
500    0.000113
501    0.000084
Name: Weight, Length: 502, dtype: float64

The current data in this file is outdated, I have mostly gotten it since it has the ticker for different stocks.

Some of the columns here are interesting and can be used to in our analysis

I think we can focus on using the following metrics for edges/nodes?(other than the tickers or the identifiers):
  - Market Cap: could show the much volatility there could be 
  - Weight: %maket cap of the company to the total market cap of S&P500


(for now I am gathering data for 500 companies, but we can choose a subset if we want)

we would definetly need to add more

In [18]:
import pandas as pd
import yfinance as yf
import ta

In [24]:
aapl = yf.download("AAPL", start="2023-01-01", end="2025-11-01")
msft = yf.download("MSFT", start="2023-01-01", end="2025-11-01")

/tmp/ipykernel_35216/3913491227.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  aapl = yf.download("AAPL", start="2023-01-01", end="2025-11-01")
[*********************100%***********************]  1 of 1 completed
/tmp/ipykernel_35216/3913491227.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  msft = yf.download("MSFT", start="2023-01-01", end="2025-11-01")
[*********************100%***********************]  1 of 1 completed

In [29]:
h = pd.merge(aapl, msft, left_index=True, right_index=True, suffixes=("_AAPL", "_MSFT"))

In [63]:
h

Price,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,MSFT,MSFT,MSFT,MSFT,MSFT
Date,,,,,,,,,,
2023-01-03,123.330650,129.079567,122.443165,128.468194,112117500,234.423569,240.460771,232.290481,237.848239,25740000
2023-01-04,124.602707,126.870724,123.340509,125.125335,89113600,224.169159,227.858008,221.096741,227.280710,50623400
2023-01-05,123.281334,125.993089,123.024955,125.361991,80962700,217.525284,222.652510,216.987118,222.310037,39585600
2023-01-06,127.817352,128.478033,123.153137,124.257564,87754700,220.088882,220.901020,214.628992,218.200429,43613600
2023-01-09,128.339981,131.554653,128.083602,128.655538,70790800,222.231750,226.263087,221.537040,221.576173,27369800
...,...,...,...,...,...,...,...,...,...,...
2025-10-27,268.809998,269.119995,264.649994,264.880005,44888200,531.520020,534.580017,529.010010,531.780029,18734700
2025-10-28,269.000000,269.890015,268.149994,268.989990,41534800,542.070007,553.719971,540.770020,550.000000,29986700
2025-10-29,269.700012,271.410004,267.109985,269.279999,51086700,541.549988,546.270020,536.729980,544.940002,36023000
2025-10-30,271.399994,274.140015,268.480011,271.989990,69886500,525.760010,534.969971,522.119995,530.479980,41023100
2025-10-31,270.369995,277.320007,269.160004,276.989990,86167100,517.809998,529.320007,515.099976,528.880005,34006400

In [62]:
h.corr()

,Price,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume
,Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,MSFT,MSFT,MSFT,MSFT,MSFT
Price,Ticker,,,,,,,,,,
Close,AAPL,1.000000,0.998286,0.998114,0.996035,-0.197792,0.794014,0.794843,0.792123,0.792783,-0.282254
High,AAPL,0.998286,1.000000,0.997157,0.997647,-0.176737,0.794685,0.796825,0.793233,0.794903,-0.274728
Low,AAPL,0.998114,0.997157,1.000000,0.998269,-0.220112,0.795474,0.796772,0.794952,0.795951,-0.291837
Open,AAPL,0.996035,0.997647,0.998269,1.000000,-0.206718,0.794477,0.796706,0.794261,0.796285,-0.286712
Volume,AAPL,-0.197792,-0.176737,-0.220112,-0.206718,1.000000,-0.106732,-0.101026,-0.113112,-0.109632,0.419016
Close,MSFT,0.794014,0.794685,0.795474,0.794477,-0.106732,1.000000,0.999182,0.999261,0.998097,-0.354529
High,MSFT,0.794843,0.796825,0.796772,0.796706,-0.101026,0.999182,1.000000,0.999062,0.999149,-0.341607
Low,MSFT,0.792123,0.793233,0.794952,0.794261,-0.113112,0.999261,0.999062,1.000000,0.999185,-0.362897
Open,MSFT,0.792783,0.794903,0.795951,0.796285,-0.109632,0.998097,0.999149,0.999185,1.000000,-0.351633
Volume,MSFT,-0.282254,-0.274728,-0.291837,-0.286712,0.419016,-0.354529,-0.341607,-0.362897,-0.351633,1.000000

In [67]:
l = h.copy()

In [68]:
# Add a new column to the entire dataframe for the filtered date range
l.loc['2023-01-01':'2023-03-31', ('new_column', 'AAPL')] = 'your_value'

In [69]:
l

Price,Close,High,Low,Open,Volume,Close,High,Low,Open,Volume,new_column
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,MSFT,MSFT,MSFT,MSFT,MSFT,AAPL
Date,,,,,,,,,,,
2023-01-03,123.330650,129.079567,122.443165,128.468194,112117500,234.423569,240.460771,232.290481,237.848239,25740000,your_value
2023-01-04,124.602707,126.870724,123.340509,125.125335,89113600,224.169159,227.858008,221.096741,227.280710,50623400,your_value
2023-01-05,123.281334,125.993089,123.024955,125.361991,80962700,217.525284,222.652510,216.987118,222.310037,39585600,your_value
2023-01-06,127.817352,128.478033,123.153137,124.257564,87754700,220.088882,220.901020,214.628992,218.200429,43613600,your_value
2023-01-09,128.339981,131.554653,128.083602,128.655538,70790800,222.231750,226.263087,221.537040,221.576173,27369800,your_value
...,...,...,...,...,...,...,...,...,...,...,...
2025-10-27,268.809998,269.119995,264.649994,264.880005,44888200,531.520020,534.580017,529.010010,531.780029,18734700,NaN
2025-10-28,269.000000,269.890015,268.149994,268.989990,41534800,542.070007,553.719971,540.770020,550.000000,29986700,NaN
2025-10-29,269.700012,271.410004,267.109985,269.279999,51086700,541.549988,546.270020,536.729980,544.940002,36023000,NaN
2025-10-30,271.399994,274.140015,268.480011,271.989990,69886500,525.760010,534.969971,522.119995,530.479980,41023100,NaN
2025-10-31,270.369995,277.320007,269.160004,276.989990,86167100,517.809998,529.320007,515.099976,528.880005,34006400,NaN

In [60]:
h.loc[:,"Close"]

Ticker            AAPL        MSFT
Date
2023-01-03  123.330650  234.423569
2023-01-04  124.602707  224.169159
2023-01-05  123.281334  217.525284
2023-01-06  127.817352  220.088882
2023-01-09  128.339981  222.231750
...                ...         ...
2025-10-27  268.809998  531.520020
2025-10-28  269.000000  542.070007
2025-10-29  269.700012  541.549988
2025-10-30  271.399994  525.760010
2025-10-31  270.369995  517.809998

[711 rows x 2 columns]

In [61]:
with open("test.csv", "w") as f:
    f.write(h.to_csv())

In [ ]:
# Example: download 2 years of data for one stock
data = yf.download("AAPL", start="2023-01-01", end="2025-01-01")

# --- Derived features ---
data["return_1d"] = data["Close"].pct_change()
data["return_5d"] = data["Close"].pct_change(5)
data["volatility_20d"] = data["Close"].pct_change().rolling(20).std()

# Trend features
data["ma_5"] = data["Close"].rolling(5).mean()
data["ma_20"] = data["Close"].rolling(20).mean()
data["ma_ratio"] = data["ma_5"] / data["ma_20"]

# RSI and MACD (from ta library)
data["rsi"] = ta.momentum.RSIIndicator(data["Close"], window=14).rsi()
macd = ta.trend.MACD(data["Close"])
data["macd"] = macd.macd()
data["macd_signal"] = macd.macd_signal()

# Volume-related
data["obv"] = ta.volume.OnBalanceVolumeIndicator(data["Close"], data["Volume"]).on_balance_volume()
data["vol_zscore"] = (data["Volume"] - data["Volume"].rolling(20).mean()) / data["Volume"].rolling(20).std()

# Price range ratio
data["price_range"] = (data["High"] - data["Low"]) / data["Close"]

In [7]:
data

Price,Close,High,Low,Open,Volume,return_1d,return_5d,volatility_20d,ma_5,ma_20,ma_ratio
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,,,,,,
Date,,,,,,,,,,,
2023-01-03,123.330650,129.079567,122.443165,128.468194,112117500,NaN,NaN,NaN,NaN,NaN,NaN
2023-01-04,124.602699,126.870716,123.340502,125.125327,89113600,0.010314,NaN,NaN,NaN,NaN,NaN
2023-01-05,123.281342,125.993097,123.024963,125.361998,80962700,-0.010605,NaN,NaN,NaN,NaN,NaN
2023-01-06,127.817360,128.478040,123.153145,124.257571,87754700,0.036794,NaN,NaN,NaN,NaN,NaN
2023-01-09,128.339996,131.554669,128.083618,128.655553,70790800,0.004089,NaN,NaN,125.474409,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2024-12-24,257.286682,257.296626,254.386957,254.586262,23234700,0.011478,0.018621,0.008828,252.264490,245.422270,1.027879
2024-12-26,258.103729,259.179926,256.718662,257.276679,27237100,0.003176,0.044225,0.008782,254.450723,246.616031,1.031769
2024-12-27,254.685867,257.784882,252.164818,256.917934,42355300,-0.013242,0.023219,0.009615,255.606616,247.645377,1.032148
2024-12-30,251.307877,252.603281,249.863009,251.337769,35557500,-0.013263,-0.008998,0.010262,255.150235,248.386246,1.027232
2024-12-31,249.534180,252.384064,248.547676,251.547039,39480700,-0.007058,-0.018999,0.010385,254.183667,248.925832,1.021122

In [1]:
import pandas as pd

df = pd.read_csv("./src/one_year_company_info.csv")

In [3]:
AAPL_EODs = df[df["Symbol"] == "AAPL"]

In [4]:
AAPL_EODs

              Date Symbol       Open       High        Low      Close   Volume
1       2024-11-19   AAPL  227.64471  230.16300  225.38005  228.13106  6210831
492     2024-11-20   AAPL  228.24159  229.89978  226.38001  228.73809  6644572
967     2024-11-21   AAPL  228.73159  229.94177  225.72115  228.34148  2783064
1429    2024-11-22   AAPL  228.32585  230.70985  227.43072  229.98764  7398453
1870    2024-11-23   AAPL  229.98385  229.99187  229.89967  229.93965     7223
...            ...    ...        ...        ...        ...        ...      ...
109004  2025-09-24   AAPL  254.24804  255.71017  251.03509  252.17756  1191725
109494  2025-09-25   AAPL  251.84378  257.16923  251.27698  256.22572  1120500
109984  2025-09-26   AAPL  256.22286  257.26499  253.58775  255.49498  1181280
110474  2025-09-29   AAPL  255.34090  255.77629  253.01125  254.04871  1020560
110964  2025-09-30   AAPL  253.79685  255.88497  253.10499  253.53476  8501984

[233 rows x 7 columns]

In [ ]:
import talib

ROCP_5 = talib.ROCP(AAPL_EODs["Close"].to_numpy(), timeperiod=5)
ROCP_20 = talib.ROCP(AAPL_EODs["Close"].to_numpy(), timeperiod=20)
NATR_5 = talib.NATR(AAPL_EODs["High"].to_numpy(), AAPL_EODs["Low"].to_numpy(), AAPL_EODs["Close"].to_numpy(), timeperiod=5)

In [11]:
NATR_5

array([       nan,        nan,        nan,        nan,        nan,
       1.26026764, 1.87947582, 2.59735968, 2.09327987, 2.76279059,
       3.21375192, 3.87010372, 3.33019727, 4.51072846, 3.89480699,
       3.12787344, 2.89997833, 2.53421621, 2.4244287 , 2.16680493,
       1.98714587, 1.61188763, 1.58995183, 1.56274337, 1.93548693,
       1.95097404, 2.76513383, 2.25875814, 2.69043458, 3.03436012,
       3.23471724, 3.44233467, 2.76858223, 2.6044036 , 2.40649268,
       1.92818479, 2.41450222, 2.12410869, 1.70930667, 1.68753523,
       1.66861159, 1.57826298, 1.28734098, 1.86338121, 1.49824301,
       2.17858209, 3.04602782, 2.81484823, 3.50637476, 3.76441403,
       3.07928099, 3.45810669, 3.14124323, 2.93544759, 2.76232703,
       2.23381333, 2.93242713, 3.24507579, 3.16804261, 3.89320282,
       5.01150801, 4.1221477 , 5.06280757, 4.5826953 , 4.30150457,
       3.69806728, 3.59754993, 2.88279107, 2.63780842, 2.83751253,
       2.77368627, 2.7537434 , 2.56843149, 2.07170784, 1.96074158,
       1.76004775, 1.64350823, 1.60201553, 1.28691796, 2.19990324,
       2.16434955, 2.42806655, 2.43497368, 2.47733077, 2.01076409,
       2.21009324, 2.23489101, 2.98823439, 2.77658528, 2.79843683,
       2.25076886, 3.16852933, 3.65072387, 3.64191722, 3.85273765,
       4.84709376, 5.15484148, 4.94289029, 4.81684402, 5.02868998,
       4.72389568, 4.03659572, 3.55453018, 3.27207031, 2.98928233,
       3.03086124, 3.1942506 , 2.9552212 , 4.34930123, 4.4730584 ,
       5.70963433, 6.60032807, 8.16245139, 8.75431385, 8.88485433,
       8.18252756, 7.99252291, 6.85845613, 6.65573124, 5.64621434,
       5.35054902, 5.20233461, 4.64893403, 4.33836512, 3.85447177,
       3.40412042, 3.03278038, 3.02560634, 3.45003099, 3.25189622,
       3.37679715, 3.09947557, 3.34044917, 3.18749532, 2.85662918,
       3.5641438 , 3.22081183, 2.89267888, 2.67061769, 2.64798732,
       2.59019501, 2.46547307, 2.61087888, 2.35462731, 2.83003113,
       2.70285882, 2.82959752, 3.28886205, 3.09654015, 2.79698867,
       2.51632782, 2.53021266, 2.47709542, 2.41886688, 2.52437523,
       2.39680408, 2.5494037 , 2.23351007, 2.24746704, 2.00460229,
       1.94912226, 1.79470108, 1.99909354, 1.92917727, 2.02525221,
       1.85954363, 1.81711254, 1.70603732, 2.08818386, 2.17227224,
       2.10642972, 2.11693607, 2.38484653, 2.16513767, 2.10234167,
       2.02453487, 1.86737978, 1.79877155, 1.78589901, 1.74607195,
       1.58777012, 1.45909099, 1.55120232, 1.48067568, 1.50437647,
       1.39514852, 1.28136962, 1.19036428, 1.30102463, 1.53384659,
       1.92423693, 2.75283956, 2.78012334, 2.48256003, 3.50011915,
       3.21726575, 3.45748905, 3.24570001, 2.98809029, 2.79017714,
       2.57203026, 2.35904159, 2.1484383 , 2.0260319 , 2.04819793,
       1.86658048, 1.81217929, 1.72770846, 1.80873497, 1.69431342,
       1.84396828, 1.65867942, 2.3492184 , 2.29085831, 2.08753575,
       1.90616171, 1.87658212, 2.02318241, 2.39583386, 2.2403155 ,
       2.35351491, 2.22040968, 2.19545546, 1.97127283, 1.96569663,
       2.18557475, 2.57378691, 2.37156507, 2.2828767 , 2.25737378,
       2.0989163 , 1.90637009, 1.74748539])

In [13]:
talib.MOM(AAPL_EODs["Close"].to_numpy(), timeperiod=5)
talib.MOM

array([          nan,           nan,           nan,           nan,
                 nan,  3.234240e+00,  6.781280e+00,  6.801990e+00,
        5.248050e+00,  7.510380e+00,  8.399680e+00,  7.360770e+00,
        7.783240e+00,  7.641420e+00,  4.969930e+00,  2.584200e+00,
        4.174620e+00,  4.787340e+00,  3.638850e+00,  4.386150e+00,
        5.429790e+00,  9.769000e-01,  3.203320e+00,  6.599960e+00,
        1.394000e-02,  1.661040e+00,  7.311130e+00,  4.442060e+00,
        1.728170e+00,  1.133424e+01,  9.658700e+00, -5.332100e-01,
       -5.818500e-01, -2.992900e+00, -7.701620e+00, -8.665860e+00,
       -1.160034e+01, -1.150227e+01, -8.535250e+00, -5.785750e+00,
       -8.312130e+00, -8.249500e-01, -9.150300e-01, -6.265650e+00,
       -7.642590e+00, -6.782130e+00, -9.047370e+00, -4.016560e+00,
       -8.597950e+00, -7.190840e+00, -5.835750e+00, -1.141653e+01,
       -1.494131e+01, -5.150160e+00, -7.637540e+00, -7.308310e+00,
        7.760980e+00,  1.424218e+01,  1.554024e+01,  2.272352e+01,
        1.276244e+01,  4.255660e+00, -8.557670e+00, -6.635580e+00,
       -1.271445e+01, -2.047480e+00, -6.658580e+00, -1.817430e+00,
       -5.371350e+00,  6.579000e-01,  4.009360e+00,  1.405364e+01,
        1.737730e+01,  1.773993e+01,  1.205138e+01,  7.714810e+00,
        4.332720e+00,  5.720000e-01,  6.178700e-01,  2.665370e+00,
        1.821010e+00, -5.936190e+00, -7.443310e+00, -3.168270e+00,
       -5.831160e+00, -8.257580e+00, -1.663220e+00, -1.988160e+00,
       -7.205860e+00, -3.111950e+00,  4.386400e-01, -1.278565e+01,
       -1.480101e+01, -1.744629e+01, -2.848018e+01, -2.531852e+01,
       -1.135313e+01, -7.989300e+00, -1.173990e+00,  3.680470e+00,
        4.509950e+00,  6.814590e+00,  1.126155e+01,  5.071260e+00,
        9.494000e+00, -5.711000e-01,  4.210800e-01, -7.941300e-01,
       -1.335213e+01, -2.000423e+01, -3.070445e+01, -3.856143e+01,
       -5.411934e+01, -1.003145e+01, -1.383518e+01,  1.043230e+01,
        1.832521e+01,  3.048953e+01, -3.111090e+00,  7.801450e+00,
       -3.111440e+00,  4.136350e+00,  4.571520e+00,  1.318216e+01,
        1.127076e+01,  1.637296e+01,  5.613900e+00,  4.520910e+00,
       -2.746660e+00, -3.460990e+00, -1.164610e+01, -9.549740e+00,
       -1.249151e+01, -7.709770e+00, -6.546430e+00,  1.156307e+01,
        1.105645e+01,  1.551930e+01,  1.358803e+01,  9.380380e+00,
       -1.296580e+00, -5.533130e+00, -1.013812e+01, -9.676630e+00,
       -1.212156e+01, -8.440720e+00,  8.314100e-01, -2.746990e+00,
       -1.080270e+00,  5.725160e+00,  2.538100e+00, -5.592210e+00,
        1.661450e+00,  4.174430e+00,  2.128800e-01, -8.529000e-02,
       -3.030880e+00, -2.144430e+00, -8.118650e+00, -4.637460e+00,
       -7.688330e+00, -2.799340e+00,  2.715620e+00,  6.029480e+00,
        3.674340e+00,  6.521990e+00,  5.224620e+00, -1.288000e-01,
        3.091370e+00,  8.111100e+00,  1.042425e+01,  1.228051e+01,
        7.854340e+00,  4.696790e+00,  1.811260e+00,  3.139900e-01,
       -3.037130e+00, -9.816400e-01, -1.284100e+00, -6.703700e-01,
       -2.225360e+00,  7.196300e-01,  4.648940e+00,  5.992830e+00,
        3.619660e+00,  3.846530e+00,  2.765470e+00,  1.426100e+00,
       -3.643240e+00, -4.986860e+00, -1.511160e+00, -1.173889e+01,
       -1.088051e+01, -8.515300e+00,  1.058790e+01,  8.691330e+00,
        2.769698e+01,  2.305251e+01,  2.689467e+01,  1.391967e+01,
        1.114744e+01,  1.202270e+00,  4.651340e+00,  2.460000e-01,
       -7.585240e+00, -7.016080e+00, -3.092990e+00, -3.867600e+00,
        5.524000e-02,  4.921630e+00,  7.144900e+00,  3.952790e+00,
        9.654430e+00,  8.142560e+00,  8.735840e+00,  6.666860e+00,
        5.878880e+00, -3.181480e+00, -1.104152e+01, -9.821160e+00,
       -5.210640e+00, -1.615000e+00,  4.352150e+00,  1.267276e+01,
        8.727220e+00,  1.170132e+01,  2.007410e+01,  1.624894e+01,
        1.245191e+01,  1.806510e+01,  9.810030e+00, -2.321410e+00,
       -6.163300e-01])

In [15]:
talib.ADXR(AAPL_EODs["High"].to_numpy(), AAPL_EODs["Low"].to_numpy(), AAPL_EODs["Close"].to_numpy(), timeperiod=5)

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan, 86.40956103, 81.98750676,
       78.49171824, 72.6858553 , 61.99385083, 54.80458886, 48.9242823 ,
       41.7851047 , 36.57687021, 36.28626558, 37.00920758, 33.38280083,
       30.48167544, 35.51440182, 40.62490561, 34.11675439, 30.4105121 ,
       32.61854477, 32.65729508, 26.87080116, 26.71546048, 27.42679848,
       26.26819305, 28.5631705 , 33.37272821, 37.91782415, 35.89077572,
       38.94384367, 41.99087951, 44.42850819, 44.41309746, 45.85361378,
       48.72603751, 51.31531309, 57.08434507, 62.13845058, 67.506507  ,
       72.09228874, 76.05748813, 79.66852755, 79.26502959, 79.04626873,
       79.16783402, 75.36972098, 71.53007982, 68.56240439, 67.98660613,
       60.96341848, 58.04538996, 53.40659474, 51.49390063, 47.61102222,
       43.80639011, 40.42441585, 37.72228597, 32.42022341, 30.63110282,
       32.08341444, 35.1891167 , 34.96882551, 37.94345139, 37.79111058,
       39.60964135, 42.53670341, 46.12178038, 45.54029618, 48.11803222,
       50.9024922 , 47.89917775, 43.7603859 , 44.21524235, 44.57912752,
       41.80169576, 38.47495892, 38.36967673, 38.28545098, 37.30154995,
       37.14577799, 43.53810423, 49.53259759, 50.13217312, 51.11920008,
       49.40768125, 49.85860848, 50.34562139, 52.2678824 , 47.25409863,
       44.18258152, 39.02088329, 35.59269415, 33.95141221, 32.69359163,
       29.31106827, 27.90312839, 27.15649732, 30.830579  , 34.66852018,
       40.21880652, 44.85792672, 52.91708793, 54.94296508, 57.4214067 ,
       58.67912037, 58.18913145, 52.80523034, 47.61009991, 42.44186716,
       38.57641945, 33.90445583, 30.01825063, 26.2243053 , 25.37464452,
       24.13081904, 24.29374808, 21.92449498, 20.64580774, 21.34694246,
       25.01431789, 26.61221045, 29.5432647 , 32.596684  , 36.76872854,
       39.08861944, 42.29369927, 45.08871845, 44.77635133, 41.28981349,
       39.17718479, 37.71803715, 37.73153084, 36.46692167, 38.30379004,
       39.77328473, 36.55093534, 35.30248398, 37.56371156, 38.80337865,
       31.19353251, 27.91000723, 25.77850827, 24.54728934, 20.42690182,
       19.07040319, 18.8764758 , 20.87899826, 22.66555097, 24.09479314,
       28.02273994, 32.27946653, 33.27724147, 34.95979191, 39.64982921,
       43.40185906, 39.10985248, 36.88814637, 40.82163413, 45.12348041,
       46.30481115, 47.87549349, 53.02880178, 57.49230521, 58.75813722,
       61.49306077, 63.88570956, 59.84803859, 55.04361587, 53.17707723,
       51.68384632, 45.4697972 , 45.56217635, 46.18887034, 47.17317781,
       48.07875012, 52.39722615, 53.90550041, 51.97971097, 54.73463541,
       51.81198213, 51.80863576, 48.19059755, 49.59172298, 46.07121722,
       47.73294158, 50.65977132, 53.00123512, 55.55177825, 58.32540532,
       62.1790856 , 64.21661847, 65.81161581, 66.12532161, 61.29359973,
       57.9945714 , 54.29675382, 50.16673201, 40.80092693, 35.83969376,
       33.09898019, 31.23328008, 32.26916236, 34.01751857, 37.66889405,
       41.13039864, 42.81916447, 42.41273259, 46.36620738, 50.06939141,
       43.91538259, 38.32726354, 39.60365001, 40.62475919, 37.52807308,
       38.33028802, 42.39515707, 45.71908661, 46.23710026, 49.28805244,
       53.52358445, 56.0764048 , 55.39119788])

In [ ]:
talib.BETA()

In [72]:
import pandas as pd
import requests
from io import StringIO

# Add headers to avoid 403 Forbidden error
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
response = requests.get(url, headers=headers)
sp500 = pd.read_html(StringIO(response.text))[0]
tickers = sp500['Symbol'].tolist()

In [79]:
sp500

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [89]:
crta_stock_data = yf.download("CTRA", start="2020-01-01", end="2025-11-01")

/tmp/ipykernel_35216/4168782735.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  crta_stock_data = yf.download("CTRA", start="2020-01-01", end="2025-11-01")
[*********************100%***********************]  1 of 1 completed

In [80]:
sp500[sp500["Founded"].str.match(r"\d{4} \(.+\)")]

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
23,AMCR,Amcor,Materials,Paper & Plastic Packaging Products & Materials,"Warmley, Bristol, United Kingdom",2019-06-07,1748790,2019 (1860)
35,AON,Aon plc,Financials,Insurance Brokers,"London, United Kingdom",1996-04-23,315293,1982 (1919)
47,T,AT&T,Communication Services,Integrated Telecommunication Services,"Dallas, Texas",1983-11-30,732717,1983 (1885)
57,BAC,Bank of America,Financials,Diversified Banks,"Charlotte, North Carolina",1976-06-30,70858,1998 (1923 / 1874)
71,BMY,Bristol Myers Squibb,Health Care,Pharmaceuticals,"New York City, New York",1957-03-04,14272,1989 (1887)
86,CARR,Carrier Global,Industrials,Building Products,"Palm Beach Gardens, Florida",2020-04-03,1783180,"2020 (1915, United Technologies spinoff)"
128,CTRA,Coterra,Energy,Oil & Gas Exploration & Production,"Houston, Texas",2008-06-23,858470,2021 (1989)
153,DOW,Dow Inc.,Materials,Commodity Chemicals,"Midland, Michigan",2019-04-01,1751788,2019 (1897)
157,DD,DuPont,Materials,Specialty Chemicals,"Wilmington, Delaware",2019-06-03,1666700,2017 (1802)
164,ELV,Elevance Health,Health Care,Managed Health Care,"Indianapolis, Indiana",2002-07-25,1156039,2014 (1946)
235,HPQ,HP Inc.,Information Technology,"Technology Hardware, Storage & Peripherals","Palo Alto, California",1974-12-31,47217,1939 (2015)
250,IFF,International Flavors & Fragrances,Materials,Specialty Chemicals,"New York City, New York",1976-03-31,51253,1958 (1889)
252,IPG,Interpublic Group of Companies (The),Communication Services,Advertising,"New York City, New York",1992-10-01,51644,1961 (1930)
265,JPM,JPMorgan Chase,Financials,Diversified Banks,"New York City, New York",1975-06-30,19617,2000 (1799 / 1871)
267,KVUE,Kenvue,Consumer Staples,Personal Care Products,"Skillman, New Jersey",2023-08-25,1944048,2022 (Johnson & Johnson spinoff)
270,KEYS,Keysight Technologies,Information Technology,Electronic Equipment & Instruments,"Santa Rosa, California",2018-11-06,1601046,2014 (1939)
276,KHC,Kraft Heinz,Consumer Staples,Packaged Foods & Meats,"Chicago, Illinois; Pittsburgh, Pennsylvania",2015-07-06,1637459,2015 (1869)
278,LHX,L3Harris,Industrials,Aerospace & Defense,"Melbourne, Florida",2008-09-22,202058,"2019 (L3 1997, Harris 1895)"
281,LW,Lamb Weston,Consumer Staples,Packaged Foods & Meats,"Eagle, Idaho",2018-12-03,1679273,2016 (1950)
296,MPC,Marathon Petroleum,Energy,Oil & Gas Refining & Marketing,"Findlay, Ohio",2011-07-01,1510295,2009 (1887)
319,TAP,Molson Coors Beverage Company,Consumer Staples,Brewers,"Chicago, Illinois",1976-06-30,24545,"2005 (Molson 1786, Coors 1873)"
322,MNST,Monster Beverage,Consumer Staples,Soft Drinks & Non-alcoholic Beverages,"Corona, California",2012-06-28,865752,2012 (1935)
325,MOS,Mosaic Company (The),Materials,Fertilizers & Agricultural Chemicals,"Tampa, Florida",2011-09-26,1285785,2004 (1865 / 1909)
326,MSI,Motorola Solutions,Information Technology,Communications Equipment,"Chicago, Illinois",1957-03-04,68505,1928 (2011)
332,NWSA,News Corp (Class A),Communication Services,Publishing,"New York City, New York",2013-08-01,1564708,2013 (News Corporation 1980)
333,NWS,News Corp (Class B),Communication Services,Publishing,"New York City, New York",2015-09-18,1564708,2013 (News Corporation 1980)
334,NEE,NextEra Energy,Utilities,Multi-Utilities,"Juno Beach, Florida",1976-06-30,753308,1984 (1925)
340,NOC,Northrop Grumman,Industrials,Aerospace & Defense,"West Falls Church, Virginia[3]",1957-03-04,1133421,"1994 (Northrop 1939, Grumman 1930)"
341,NCLH,Norwegian Cruise Line Holdings,Consumer Discretionary,"Hotels, Resorts & Cruise Lines","Miami-Dade County, Florida[4]",2017-10-13,1513761,2011 (1966)
354,OTIS,Otis Worldwide,Industrials,Industrial Machinery & Supplies & Components,"Farmington, Connecticut",2020-04-03,1781335,"2020 (1853, United Technologies spinoff)"
359,PSKY,Paramount Skydance Corporation,Communication Services,Movies & Entertainment,"Los Angeles, California",1994-09-30,2041610,2025 (Paramount Pictures 1912)
368,PM,Philip Morris International,Consumer Staples,Tobacco,"New York City, New York",2008-03-31,1413329,2008 (1847)
369,PSX,Phillips 66,Energy,Oil & Gas Refining & Marketing,"Houston, Texas",2012-05-01,1534701,2012 (1917)
395,RSG,Republic Services,Industrials,Environmental & Facilities Services,"Phoenix, Arizona",2008-12-05,1060391,1998 (1981)
444,TMO,Thermo Fisher Scientific,Health Care,Life Sciences Tools & Services,"Waltham, Massachusetts",2004-08-03,97745,2006 (1902)
471,VZ,Verizon,Communication Services,Integrated Telecommunication Services,"New York City, New York",1983-11-30,732712,1983 (1877)
480,WAB,Wabtec,Industrials,Construction Machinery & Heavy Transportation ...,"Pittsburgh, Pennsylvania",2019-02-27,943452,1999 (1869)
483,WBD,Warner Bros. Discovery,Communication Services,Broadcasting,"New York City, New York",2022-04-11,1437107,2022 (Warner Bros. 1923)

In [100]:
ctra = yf.Ticker("CTRA")

In [108]:
q_income = ctra.quarterly_income_stmt
q_balance = ctra.quarterly_balance_sheet
q_earnings = ctra.quarterly_balance_sheet

In [95]:
prices = crta_stock_data.loc["2020-01-01":"2021-01-01", "Close"]

In [110]:
ctra.get_history_metadata()

{'currency': 'USD',
 'symbol': 'CTRA',
 'exchangeName': 'NYQ',
 'fullExchangeName': 'NYSE',
 'instrumentType': 'EQUITY',
 'firstTradeDate': 634487400,
 'regularMarketTime': 1762549202,
 'hasPrePostMarketData': True,
 'gmtoffset': -18000,
 'timezone': 'EST',
 'exchangeTimezoneName': 'America/New_York',
 'regularMarketPrice': 26.57,
 'fiftyTwoWeekHigh': 29.95,
 'fiftyTwoWeekLow': 22.33,
 'regularMarketDayHigh': 26.79,
 'regularMarketDayLow': 26.17,
 'regularMarketVolume': 7658930,
 'longName': 'Coterra Energy Inc.',
 'shortName': 'Coterra Energy Inc.',
 'chartPreviousClose': 24.39,
 'previousClose': 26.37,
 'scale': 3,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'EST',
   'start': 1762765200,
   'end': 1762785000,
   'gmtoffset': -18000},
  'regular': {'timezone': 'EST',
   'start': 1762785000,
   'end': 1762808400,
   'gmtoffset': -18000},
  'post': {'timezone': 'EST',
   'start': 1762808400,
   'end': 1762822800,
   'gmtoffset': -18000}},
 'tradingPeriods':                                           pre_start                   pre_end  \
 Date
 2025-11-04 00:00:00-05:00 2025-11-04 04:00:00-05:00 2025-11-04 09:30:00-05:00
 2025-11-05 00:00:00-05:00 2025-11-05 04:00:00-05:00 2025-11-05 09:30:00-05:00
 2025-11-06 00:00:00-05:00 2025-11-06 04:00:00-05:00 2025-11-06 09:30:00-05:00
 2025-11-07 00:00:00-05:00 2025-11-07 04:00:00-05:00 2025-11-07 09:30:00-05:00
 2025-11-10 00:00:00-05:00 2025-11-10 04:00:00-05:00 2025-11-10 09:30:00-05:00

                                               start                       end  \
 Date
 2025-11-04 00:00:00-05:00 2025-11-04 09:30:00-05:00 2025-11-04 16:00:00-05:00
 2025-11-05 00:00:00-05:00 2025-11-05 09:30:00-05:00 2025-11-05 16:00:00-05:00
 2025-11-06 00:00:00-05:00 2025-11-06 09:30:00-05:00 2025-11-06 16:00:00-05:00
 2025-11-07 00:00:00-05:00 2025-11-07 09:30:00-05:00 2025-11-07 16:00:00-05:00
 2025-11-10 00:00:00-05:00 2025-11-10 09:30:00-05:00 2025-11-10 16:00:00-05:00

                                          post_start                  post_end
 Date
 2025-11-04 00:00:00-05:00 2025-11-04 16:00:00-05:00 2025-11-04 20:00:00-05:00
 2025-11-05 00:00:00-05:00 2025-11-05 16:00:00-05:00 2025-11-05 20:00:00-05:00
 2025-11-06 00:00:00-05:00 2025-11-06 16:00:00-05:00 2025-11-06 20:00:00-05:00
 2025-11-07 00:00:00-05:00 2025-11-07 16:00:00-05:00 2025-11-07 20:00:00-05:00
 2025-11-10 00:00:00-05:00 2025-11-10 16:00:00-05:00 2025-11-10 20:00:00-05:00  ,
 'dataGranularity': '1h',
 'range': '5d',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max'],
 'lastTrade': {'Price': np.float64(26.62),
  'Time': Timestamp('2025-11-10 06:10:18-0500', tz='America/New_York')}}

In [118]:
import yfinance as yf

ticker = yf.Ticker("CTRA")
q_earnings = ticker.get_earnings_dates()
q_earnings.sort_index()

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2020-02-20 16:00:00-05:00          0.31          0.30        -1.98
2020-04-30 16:00:00-04:00          0.14          0.14         3.63
2020-07-30 16:00:00-04:00          0.02          0.05       152.65
2020-10-29 16:00:00-04:00          0.07          0.09        35.24
2021-02-23 16:00:00-05:00          0.20          0.26        27.80
2021-04-29 16:00:00-04:00          0.36          0.38         6.47
2021-07-30 07:00:00-04:00          0.27          0.26        -3.61
2021-11-03 06:00:00-04:00          0.54          0.52        -3.09
2022-02-23 16:00:00-05:00          1.02          0.83       -18.59
2022-05-02 16:00:00-04:00          0.82          1.01        23.21
2022-08-02 16:00:00-04:00          1.28          1.35         5.80
2022-11-03 16:00:00-04:00          1.39          1.42         2.24
2023-02-22 16:00:00-05:00          1.10          1.16         5.90
2023-05-04 16:00:00-04:00          0.70          0.87        24.11
2023-08-07 16:00:00-04:00          0.33          0.39        17.62
2023-11-06 16:00:00-05:00          0.43          0.50        15.35
2024-02-22 16:00:00-05:00          0.54          0.52        -4.14
2024-05-02 16:00:00-04:00          0.41          0.51        23.72
2024-08-01 16:00:00-04:00          0.39          0.37        -4.73
2024-10-31 16:00:00-04:00          0.34          0.32        -6.97
2025-02-24 17:00:00-05:00          0.43          0.49        14.29
2025-05-05 17:00:00-04:00          0.80          0.80         0.55
2025-08-04 17:00:00-04:00          0.45          0.48         6.96
2025-11-03 16:00:00-05:00          0.43          0.41        -4.77
2026-02-23 16:00:00-05:00          0.55           NaN          NaN

In [123]:
ticker.

            epsActual  epsEstimate  epsDifference  surprisePercent
quarter
2024-12-31       0.49      0.42873           0.06           0.1429
2025-03-31       0.80      0.79560           0.00           0.0055
2025-06-30       0.48      0.44876           0.03           0.0696
2025-09-30       0.41      0.43052          -0.02          -0.0477

In [1]:
import requests
url = "https://www.sec.gov/files/company_tickers.json"
headers = {'User-Agent': 'YourAppName/1.0 (hvgupta@outlook.in)'}  # Replace with your details
response = requests.get(url, headers=headers)
if response.status_code != 200:
    raise Exception(f"Failed to fetch data: {response.status_code}")

In [2]:
response.json()

{'0': {'cik_str': 1045810, 'ticker': 'NVDA', 'title': 'NVIDIA CORP'},
 '1': {'cik_str': 789019, 'ticker': 'MSFT', 'title': 'MICROSOFT CORP'},
 '2': {'cik_str': 320193, 'ticker': 'AAPL', 'title': 'Apple Inc.'},
 '3': {'cik_str': 1652044, 'ticker': 'GOOGL', 'title': 'Alphabet Inc.'},
 '4': {'cik_str': 1018724, 'ticker': 'AMZN', 'title': 'AMAZON COM INC'},
 '5': {'cik_str': 1326801, 'ticker': 'META', 'title': 'Meta Platforms, Inc.'},
 '6': {'cik_str': 1730168, 'ticker': 'AVGO', 'title': 'Broadcom Inc.'},
 '7': {'cik_str': 1067983,
  'ticker': 'BRK-B',
  'title': 'BERKSHIRE HATHAWAY INC'},
 '8': {'cik_str': 1318605, 'ticker': 'TSLA', 'title': 'Tesla, Inc.'},
 '9': {'cik_str': 19617, 'ticker': 'JPM', 'title': 'JPMORGAN CHASE & CO'},
 '10': {'cik_str': 1341439, 'ticker': 'ORCL', 'title': 'ORACLE CORP'},
 '11': {'cik_str': 104169, 'ticker': 'WMT', 'title': 'Walmart Inc.'},
 '12': {'cik_str': 1403161, 'ticker': 'V', 'title': 'VISA INC.'},
 '13': {'cik_str': 59478, 'ticker': 'LLY', 'title': 'ELI LILLY & Co'},
 '14': {'cik_str': 884394, 'ticker': 'SPY', 'title': 'SPDR S&P 500 ETF TRUST'},
 '15': {'cik_str': 1141391, 'ticker': 'MA', 'title': 'Mastercard Inc'},
 '16': {'cik_str': 1065280, 'ticker': 'NFLX', 'title': 'NETFLIX INC'},
 '17': {'cik_str': 34088, 'ticker': 'XOM', 'title': 'EXXON MOBIL CORP'},
 '18': {'cik_str': 200406, 'ticker': 'JNJ', 'title': 'JOHNSON & JOHNSON'},
 '19': {'cik_str': 1577552,
  'ticker': 'BABA',
  'title': 'Alibaba Group Holding Ltd'},
 '20': {'cik_str': 1321655,
  'ticker': 'PLTR',
  'title': 'Palantir Technologies Inc.'},
 '21': {'cik_str': 909832,
  'ticker': 'COST',
  'title': 'COSTCO WHOLESALE CORP /NEW'},
 '22': {'cik_str': 354950, 'ticker': 'HD', 'title': 'HOME DEPOT, INC.'},
 '23': {'cik_str': 1551152, 'ticker': 'ABBV', 'title': 'AbbVie Inc.'},
 '24': {'cik_str': 70858,
  'ticker': 'BAC',
  'title': 'BANK OF AMERICA CORP /DE/'},
 '25': {'cik_str': 937966, 'ticker': 'ASML', 'title': 'ASML HOLDING NV'},
 '26': {'cik_str': 80424, 'ticker': 'PG', 'title': 'PROCTER & GAMBLE Co'},
 '27': {'cik_str': 93410, 'ticker': 'CVX', 'title': 'CHEVRON CORP'},
 '28': {'cik_str': 40545, 'ticker': 'GE', 'title': 'GENERAL ELECTRIC CO'},
 '29': {'cik_str': 1000184, 'ticker': 'SAP', 'title': 'SAP SE'},
 '30': {'cik_str': 1283699, 'ticker': 'TMUS', 'title': 'T-Mobile US, Inc.'},
 '31': {'cik_str': 21344, 'ticker': 'KO', 'title': 'COCA COLA CO'},
 '32': {'cik_str': 731766, 'ticker': 'UNH', 'title': 'UNITEDHEALTH GROUP INC'},
 '33': {'cik_str': 858877, 'ticker': 'CSCO', 'title': 'CISCO SYSTEMS, INC.'},
 '34': {'cik_str': 2488,
  'ticker': 'AMD',
  'title': 'ADVANCED MICRO DEVICES INC'},
 '35': {'cik_str': 72971,
  'ticker': 'WFC',
  'title': 'WELLS FARGO & COMPANY/MN'},
 '36': {'cik_str': 51143,
  'ticker': 'IBM',
  'title': 'INTERNATIONAL BUSINESS MACHINES CORP'},
 '37': {'cik_str': 895421, 'ticker': 'MS', 'title': 'MORGAN STANLEY'},
 '38': {'cik_str': 1413329,
  'ticker': 'PM',
  'title': 'Philip Morris International Inc.'},
 '39': {'cik_str': 2070829,
  'ticker': 'CYATY',
  'title': 'Contemporary Amperex Technology Co., Limited/ADR'},
 '40': {'cik_str': 1094517, 'ticker': 'TM', 'title': 'TOYOTA MOTOR CORP/'},
 '41': {'cik_str': 886982, 'ticker': 'GS', 'title': 'GOLDMAN SACHS GROUP INC'},
 '42': {'cik_str': 1089113, 'ticker': 'HSBC', 'title': 'HSBC HOLDINGS PLC'},
 '43': {'cik_str': 353278, 'ticker': 'NVO', 'title': 'NOVO NORDISK A S'},
 '44': {'cik_str': 1751008, 'ticker': 'APP', 'title': 'AppLovin Corp'},
 '45': {'cik_str': 1114448, 'ticker': 'NVS', 'title': 'NOVARTIS AG'},
 '46': {'cik_str': 4962, 'ticker': 'AXP', 'title': 'AMERICAN EXPRESS CO'},
 '47': {'cik_str': 1067839,
  'ticker': 'QQQ',
  'title': 'INVESCO QQQ TRUST, SERIES 1'},
 '48': {'cik_str': 1108524, 'ticker': 'CRM', 'title': 'Salesforce, Inc.'},
 '49': {'cik_str': 1800, 'ticker': 'ABT', 'title': 'ABBOTT LABORATORIES'},
 '50': {'cik_str': 901832, 'ticker': 'AZN', 'title': 'ASTRAZENECA PLC'},
 '51': {'cik_str': 1707925, 'ticker': 'LIN', 'title': 'LINDE PLC'},
 '52': {'cik_str': 18230, 'ticker': 'CAT', 'title': 'CATERPILLAR INC'},
 '53': {'cik_str': 101829, 'ticker': 'RTX', 'title': 'RTX Corp'},
 '54': {'cik_str': 1393818, 'ticker': 'BX', 'title': 'Blackstone Inc.'},
 '55': {'cik_str': 63908, 'ticker': 'MCD', 'title': 'MCDONALDS CORP'},
 '56': {'cik_str': 1306965, 'ticker': 'SHEL', 'title': 'Shell plc'},
 '57': {'cik_str': 1000275, 'ticker': 'RY', 'title': 'ROYAL BANK OF CANADA'},
 '58': {'cik_str': 732717, 'ticker': 'T', 'title': 'AT&T INC.'},
 '59': {'cik_str': 1744489, 'ticker': 'DIS', 'title': 'Walt Disney Co'},
 '60': {'cik_str': 310158, 'ticker': 'MRK', 'title': 'Merck & Co., Inc.'},
 '61': {'cik_str': 1373715, 'ticker': 'NOW', 'title': 'ServiceNow, Inc.'},
 '62': {'cik_str': 1543151,
  'ticker': 'UBER',
  'title': 'Uber Technologies, Inc'},
 '63': {'cik_str': 896878, 'ticker': 'INTU', 'title': 'INTUIT INC.'},
 '64': {'cik_str': 1594805, 'ticker': 'SHOP', 'title': 'SHOPIFY INC.'},
 '65': {'cik_str': 77476, 'ticker': 'PEP', 'title': 'PEPSICO INC'},
 '66': {'cik_str': 831001, 'ticker': 'C', 'title': 'CITIGROUP INC'},
 '67': {'cik_str': 1737806, 'ticker': 'PDD', 'title': 'PDD Holdings Inc.'},
 '68': {'cik_str': 97745,
  'ticker': 'TMO',
  'title': 'THERMO FISHER SCIENTIFIC INC.'},
 '69': {'cik_str': 732712,
  'ticker': 'VZ',
  'title': 'VERIZON COMMUNICATIONS INC'},
 '70': {'cik_str': 723125, 'ticker': 'MU', 'title': 'MICRON TECHNOLOGY INC'},
 '71': {'cik_str': 2012383, 'ticker': 'BLK', 'title': 'BlackRock, Inc.'},
 '72': {'cik_str': 67088,
  'ticker': 'MUFG',
  'title': 'MITSUBISHI UFJ FINANCIAL GROUP INC'},
 '73': {'cik_str': 97476, 'ticker': 'TXN', 'title': 'TEXAS INSTRUMENTS INC'},
 '74': {'cik_str': 1596532,
  'ticker': 'ANET',
  'title': 'Arista Networks, Inc.'},
 '75': {'cik_str': 804328, 'ticker': 'QCOM', 'title': 'QUALCOMM INC/DE'},
 '76': {'cik_str': 1075531,
  'ticker': 'BKNG',
  'title': 'Booking Holdings Inc.'},
 '77': {'cik_str': 316709, 'ticker': 'SCHW', 'title': 'SCHWAB CHARLES CORP'},
 '78': {'cik_str': 1144967, 'ticker': 'HDB', 'title': 'HDFC BANK LTD'},
 '79': {'cik_str': 946770, 'ticker': 'DTEGY', 'title': 'DEUTSCHE TELEKOM AG'},
 '80': {'cik_str': 707549, 'ticker': 'LRCX', 'title': 'LAM RESEARCH CORP'},
 '81': {'cik_str': 64040, 'ticker': 'SPGI', 'title': 'S&P Global Inc.'},
 '82': {'cik_str': 12927, 'ticker': 'BA', 'title': 'BOEING CO'},
 '83': {'cik_str': 1996810, 'ticker': 'GEV', 'title': 'GE Vernova Inc.'},
 '84': {'cik_str': 6951,
  'ticker': 'AMAT',
  'title': 'APPLIED MATERIALS INC /DE'},
 '85': {'cik_str': 313838, 'ticker': 'SONY', 'title': 'Sony Group Corp'},
 '86': {'cik_str': 50863, 'ticker': 'INTC', 'title': 'INTEL CORP'},
 '87': {'cik_str': 1035267,
  'ticker': 'ISRG',
  'title': 'INTUITIVE SURGICAL INC'},
 '88': {'cik_str': 753308, 'ticker': 'NEE', 'title': 'NEXTERA ENERGY INC'},
 '89': {'cik_str': 217410, 'ticker': 'UL', 'title': 'UNILEVER PLC'},
 '90': {'cik_str': 109198, 'ticker': 'TJX', 'title': 'TJX COMPANIES INC /DE/'},
 '91': {'cik_str': 1467373, 'ticker': 'ACN', 'title': 'Accenture plc'},
 '92': {'cik_str': 891478, 'ticker': 'SAN', 'title': 'Banco Santander, S.A.'},
 '93': {'cik_str': 796343, 'ticker': 'ADBE', 'title': 'ADOBE INC.'},
 '94': {'cik_str': 310764, 'ticker': 'SYK', 'title': 'STRYKER CORP'},
 '95': {'cik_str': 1973239, 'ticker': 'ARM', 'title': 'ARM HOLDINGS PLC /UK'},
 '96': {'cik_str': 820313, 'ticker': 'APH', 'title': 'AMPHENOL CORP /DE/'},
 '97': {'cik_str': 318154, 'ticker': 'AMGN', 'title': 'AMGEN INC'},
 '98': {'cik_str': 811809, 'ticker': 'BHP', 'title': 'BHP Group Ltd'},
 '99': {'cik_str': 885725, 'ticker': 'BSX', 'title': 'BOSTON SCIENTIFIC CORP'},
 '100': {'cik_str': 80661, 'ticker': 'PGR', 'title': 'PROGRESSIVE CORP/OH/'},
 '101': {'cik_str': 927628,
  'ticker': 'COF',
  'title': 'CAPITAL ONE FINANCIAL CORP'},
 '102': {'cik_str': 1551182, 'ticker': 'ETN', 'title': 'Eaton Corp plc'},
 '103': {'cik_str': 60667, 'ticker': 'LOW', 'title': 'LOWES COMPANIES INC'},
 '104': {'cik_str': 1639920,
  'ticker': 'SPOT',
  'title': 'Spotify Technology S.A.'},
 '105': {'cik_str': 319201, 'ticker': 'KLAC', 'title': 'KLA CORP'},
 '106': {'cik_str': 882095,
  'ticker': 'GILD',
  'title': 'GILEAD SCIENCES, INC.'},
 '107': {'cik_str': 879764, 'ticker': 'TTE', 'title': 'TotalEnergies SE'},
 '108': {'cik_str': 1327567,
  'ticker': 'PANW',
  'title': 'Palo Alto Networks Inc'},
 '109': {'cik_str': 78003, 'ticker': 'PFE', 'title': 'PFIZER INC'},
 '110': {'cik_str': 313616, 'ticker': 'DHR', 'title': 'DANAHER CORP /DE/'},
 '111': {'cik_str': 773840,
  'ticker': 'HON',
  'title': 'HONEYWELL INTERNATIONAL INC'},
 '112': {'cik_str': 100885, 'ticker': 'UNP', 'title': 'UNION PACIFIC CORP'},
 '113': {'cik_str': 2046954, 'ticker': 'UTX', 'title': 'Ultratrex Inc.'},
 '114': {'cik_str': 947263, 'ticker': 'TD', 'title': 'TORONTO DOMINION BANK'},
 '115': {'cik_str': 1099590, 'ticker': 'MELI', 'title': 'MERCADOLIBRE INC'},
 '116': {'cik_str': 887028, 'ticker': 'RTNTF', 'title': 'RIO TINTO LTD'},
 '117': {'cik_str': 315189, 'ticker': 'DE', 'title': 'DEERE & CO'},
 '118': {'cik_str': 1610520, 'ticker': 'UBS', 'title': 'UBS Group AG'},
 '119': {'cik_str': 1404912, 'ticker': 'KKR', 'title': 'KKR & Co. Inc.'},
 '120': {'cik_str': 1535527,
  'ticker': 'CRWD',
  'title': 'CrowdStrike Holdings, Inc.'},
 '121': {'cik_str': 1783879,
  'ticker': 'HOOD',
  'title': 'Robinhood Markets, Inc.'},
 '122': {'cik_str': 1613103, 'ticker': 'MDT', 'title': 'Medtronic plc'},
 '123': {'cik_str': 1121404, 'ticker': 'SNY', 'title': 'Sanofi'},
 '124': {'cik_str': 47710, 'ticker': 'HTHIY', 'title': 'HITACHI LTD'},
 '125': {'cik_str': 6281, 'ticker': 'ADI', 'title': 'ANALOG DEVICES INC'},
 '126': {'cik_str': 1163165, 'ticker': 'COP', 'title': 'CONOCOPHILLIPS'},
 '127': {'cik_str': 1668717,
  'ticker': 'BUD',
  'title': 'Anheuser-Busch InBev SA/NV'},
 '128': {'cik_str': 8670,
  'ticker': 'ADP',
  'title': 'AUTOMATIC DATA PROCESSING INC'},
 '129': {'cik_str': 1381197,
  'ticker': 'IBKR',
  'title': 'Interactive Brokers Group, Inc.'},
 '130': {'cik_str': 1792789, 'ticker': 'DASH', 'title': 'DoorDash, Inc.'},
 '131': {'cik_str': 1166691, 'ticker': 'CMCSA', 'title': 'COMCAST CORP'},
 '132': {'cik_str': 1303523,
  'ticker': 'BTI',
  'title': 'British American Tobacco p.l.c.'},
 '133': {'cik_str': 936468, 'ticker': 'LMT', 'title': 'LOCKHEED MARTIN CORP'},
 '134': {'cik_str': 766704, 'ticker': 'WELL', 'title': 'WELLTOWER INC.'},
 '135': {'cik_str': 896159, 'ticker': 'CB', 'title': 'Chubb Ltd'},
 '136': {'cik_str': 764180, 'ticker': 'MO', 'title': 'ALTRIA GROUP, INC.'},
 '137': {'cik_str': 842180,
  'ticker': 'BBVA',
  'title': 'BANCO BILBAO VIZCAYA ARGENTARIA, S.A.'},
 '138': {'cik_str': 883241, 'ticker': 'SNPS', 'title': 'SYNOPSYS INC'},
 '139': {'cik_str': 863064, 'ticker': 'RIO', 'title': 'RIO TINTO PLC'},
 '140': {'cik_str': 1022837,
  'ticker': 'SMFG',
  'title': 'SUMITOMO MITSUI FINANCIAL GROUP, INC.'},
 '141': {'cik_str': 895728, 'ticker': 'ENB', 'title': 'ENBRIDGE INC'},
 '142': {'cik_str': 1103838, 'ticker': 'IBN', 'title': 'ICICI BANK LTD'},
 '143': {'cik_str': 1703399, 'ticker': 'SE', 'title': 'Sea Ltd'},
 '144': {'cik_str': 1045609, 'ticker': 'PLD', 'title': 'Prologis, Inc.'},
 '145': {'cik_str': 1868275,
  'ticker': 'CEG',
  'title': 'Constellation Energy Corp'},
 '146': {'cik_str': 1001085, 'ticker': 'BN', 'title': 'BROOKFIELD Corp /ON/'},
 '147': {'cik_str': 875320,
  'ticker': 'VRTX',
  'title': 'VERTEX PHARMACEUTICALS INC / MA'},
 '148': {'cik_str': 320187, 'ticker': 'NKE', 'title': 'NIKE, Inc.'},
 '149': {'cik_str': 92122, 'ticker': 'SO', 'title': 'SOUTHERN CO'},
 '150': {'cik_str': 860730, 'ticker': 'HCA', 'title': 'HCA Healthcare, Inc.'},
 '151': {'cik_str': 62709,
  'ticker': 'MMC',
  'title': 'MARSH & MCLENNAN COMPANIES, INC.'},
 '152': {'cik_str': 1001838,
  'ticker': 'SCCO',
  'title': 'SOUTHERN COPPER CORP/'},
 '153': {'cik_str': 1315098, 'ticker': 'RBLX', 'title': 'Roblox Corp'},
 '154': {'cik_str': 1156375, 'ticker': 'CME', 'title': 'CME GROUP INC.'},
 '155': {'cik_str': 829224, 'ticker': 'SBUX', 'title': 'STARBUCKS CORP'},
 '156': {'cik_str': 1571949,
  'ticker': 'ICE',
  'title': 'Intercontinental Exchange, Inc.'},
 '157': {'cik_str': 1110646, 'ticker': 'NTES', 'title': 'NetEase, Inc.'},
 '158': {'cik_str': 64803, 'ticker': 'CVS', 'title': 'CVS HEALTH Corp'},
 '159': {'cik_str': 1326160, 'ticker': 'DUK', 'title': 'Duke Energy CORP'},
 '160': {'cik_str': 76334, 'ticker': 'PH', 'title': 'Parker-Hannifin Corp'},
 '161': {'cik_str': 813672,
  'ticker': 'CDNS',
  'title': 'CADENCE DESIGN SYSTEMS INC'},
 '162': {'cik_str': 927653, 'ticker': 'MCK', 'title': 'MCKESSON CORP'},
 '163': {'cik_str': 1937926,
  'ticker': 'BAM',
  'title': 'Brookfield Asset Management Ltd.'},
 '164': {'cik_str': 927971,
  'ticker': 'BMO',
  'title': 'BANK OF MONTREAL /CAN/'},
 '165': {'cik_str': 1164727, 'ticker': 'NEM', 'title': 'NEWMONT Corp /DE/'},
 '166': {'cik_str': 1050446, 'ticker': 'MSTR', 'title': 'Strategy Inc'},
 '167': {'cik_str': 1222333, 'ticker': 'GLD', 'title': 'SPDR GOLD TRUST'},
 '168': {'cik_str': 898173,
  'ticker': 'ORLY',
  'title': 'O REILLY AUTOMOTIVE INC'},
 '169': {'cik_str': 1466258,
  'ticker': 'TT',
  'title': 'Trane Technologies plc'},
 '170': {'cik_str': 1053507,
  'ticker': 'AMT',
  'title': 'AMERICAN TOWER CORP /MA/'},
 '171': {'cik_str': 823768, 'ticker': 'WM', 'title': 'WASTE MANAGEMENT INC'},
 '172': {'cik_str': 14272,
  'ticker': 'BMY',
  'title': 'BRISTOL MYERS SQUIBB CO'},
 '173': {'cik_str': 1571996,
  'ticker': 'DELL',
  'title': 'Dell Technologies Inc.'},
 '174': {'cik_str': 313807, 'ticker': 'BP', 'title': 'BP PLC'},
 '175': {'cik_str': 40533, 'ticker': 'GD', 'title': 'GENERAL DYNAMICS CORP'},
 '176': {'cik_str': 884887,
  'ticker': 'RCL',
  'title': 'ROYAL CARIBBEAN CRUISES LTD'},
 '177': {'cik_str': 929869, 'ticker': 'RELX', 'title': 'RELX PLC'},
 '178': {'cik_str': 1059556, 'ticker': 'MCO', 'title': 'MOODYS CORP /DE/'},
 '179': {'cik_str': 1679788,
  'ticker': 'COIN',
  'title': 'Coinbase Global, Inc.'},
 '180': {'cik_str': 1648416, 'ticker': 'RACE', 'title': 'Ferrari N.V.'},
 '181': {'cik_str': 89800, 'ticker': 'SHW', 'title': 'SHERWIN WILLIAMS CO'},
 '182': {'cik_str': 1133421,
  'ticker': 'NOC',
  'title': 'NORTHROP GRUMMAN CORP /DE/'},
 '183': {'cik_str': 1335730,
  'ticker': 'MFG',
  'title': 'MIZUHO FINANCIAL GROUP INC'},
 '184': {'cik_str': 2809, 'ticker': 'AEM', 'title': 'AGNICO EAGLE MINES LTD'},
 '185': {'cik_str': 1131399, 'ticker': 'GSK', 'title': 'GSK plc'},
 '186': {'cik_str': 723254, 'ticker': 'CTAS', 'title': 'CINTAS CORP'},
 '187': {'cik_str': 66740, 'ticker': 'MMM', 'title': '3M CO'},
 '188': {'cik_str': 1103982,
  'ticker': 'MDLZ',
  'title': 'Mondelez International, Inc.'},
 '189': {'cik_str': 895564,
  'ticker': 'BAESY',
  'title': 'BAE SYSTEMS PLC /FI/'},
 '190': {'cik_str': 1119639,
  'ticker': 'PBR',
  'title': 'PETROBRAS - PETROLEO BRASILEIRO SA'},
 '191': {'cik_str': 2039784,
  'ticker': 'MGCLY',
  'title': 'Midea Group Co., Ltd./ADR'},
 '192': {'cik_str': 9631, 'ticker': 'BNS', 'title': 'BANK OF NOVA SCOTIA'},
 '193': {'cik_str': 1075124,
  'ticker': 'TRI',
  'title': 'THOMSON REUTERS CORP /CAN/'},
 '194': {'cik_str': 713676,
  'ticker': 'PNC',
  'title': 'PNC FINANCIAL SERVICES GROUP, INC.'},
 '195': {'cik_str': 1858681,
  'ticker': 'APO',
  'title': 'Apollo Global Management, Inc.'},
 '196': {'cik_str': 354190,
  'ticker': 'AJG',
  'title': 'Arthur J. Gallagher & Co.'},
 '197': {'cik_str': 1640147, 'ticker': 'SNOW', 'title': 'Snowflake Inc.'},
 '198': {'cik_str': 31462, 'ticker': 'ECL', 'title': 'ECOLAB INC.'},
 '199': {'cik_str': 1390777,
  'ticker': 'BK',
  'title': 'Bank of New York Mellon Corp'},
 '200': {'cik_str': 4281, 'ticker': 'HWM', 'title': 'Howmet Aerospace Inc.'},
 '201': {'cik_str': 1691493, 'ticker': 'NU', 'title': 'Nu Holdings Ltd.'},
 '202': {'cik_str': 849395, 'ticker': 'CRH', 'title': 'CRH PUBLIC LTD CO'},
 '203': {'cik_str': 1101239, 'ticker': 'EQIX', 'title': 'EQUINIX INC'},
 '204': {'cik_str': 1739940, 'ticker': 'CI', 'title': 'Cigna Group'},
 '205': {'cik_str': 315293, 'ticker': 'AON', 'title': 'Aon plc'},
 '206': {'cik_str': 1039765, 'ticker': 'ING', 'title': 'ING GROEP NV'},
 '207': {'cik_str': 49826,
  'ticker': 'ITW',
  'title': 'ILLINOIS TOOL WORKS INC'},
 '208': {'cik_str': 1477333, 'ticker': 'NET', 'title': 'Cloudflare, Inc.'},
 '209': {'cik_str': 68505,
  'ticker': 'MSI',
  'title': 'Motorola Solutions, Inc.'},
 '210': {'cik_str': 1158838, 'ticker': 'ATEYY', 'title': 'ADVANTEST CORP'},
 '211': {'cik_str': 36104, 'ticker': 'USB', 'title': 'US BANCORP \\DE\\'},
 '212': {'cik_str': 1559720, 'ticker': 'ABNB', 'title': 'Airbnb, Inc.'},
 '213': {'cik_str': 1132597,
  'ticker': 'ITUB',
  'title': 'Itau Unibanco Holding S.A.'},
 '214': {'cik_str': 1045520,
  'ticker': 'CM',
  'title': 'CANADIAN IMPERIAL BANK OF COMMERCE /CAN/'},
 '215': {'cik_str': 1260221, 'ticker': 'TDG', 'title': 'TransDigm Group INC'},
 '216': {'cik_str': 32604, 'ticker': 'EMR', 'title': 'EMERSON ELECTRIC CO'},
 '217': {'cik_str': 1048286,
  'ticker': 'MAR',
  'title': 'MARRIOTT INTERNATIONAL INC /MD/'},
 '218': {'cik_str': 312069, 'ticker': 'BCS', 'title': 'BARCLAYS PLC'},
 '219': {'cik_str': 1090727,
  'ticker': 'UPS',
  'title': 'UNITED PARCEL SERVICE INC'},
 '220': {'cik_str': 1156039,
  'ticker': 'ELV',
  'title': 'Elevance Health, Inc.'},
 '221': {'cik_str': 1060391,
  'ticker': 'RSG',
  'title': 'REPUBLIC SERVICES, INC.'},
 '222': {'cik_str': 1004315, 'ticker': 'NGG', 'title': 'NATIONAL GRID PLC'},
 '223': {'cik_str': 866787, 'ticker': 'AZO', 'title': 'AUTOZONE INC'},
 '224': {'cik_str': 1835632,
  'ticker': 'MRVL',
  'title': 'Marvell Technology, Inc.'},
 '225': {'cik_str': 798354, 'ticker': 'FI', 'title': 'FISERV INC'},
 '226': {'cik_str': 833444,
  'ticker': 'JCI',
  'title': 'Johnson Controls International plc'},
 '227': {'cik_str': 1278680, 'ticker': 'IAU', 'title': 'ISHARES GOLD TRUST'},
 '228': {'cik_str': 107263,
  'ticker': 'WMB',
  'title': 'WILLIAMS COMPANIES, INC.'},
 '229': {'cik_str': 24741, 'ticker': 'GLW', 'title': 'CORNING INC /NY'},
 '230': {'cik_str': 769397, 'ticker': 'ADSK', 'title': 'Autodesk, Inc.'},
 '231': {'cik_str': 1159508,
  'ticker': 'DB',
  'title': 'DEUTSCHE BANK AKTIENGESELLSCHAFT'},
 '232': {'cik_str': 1555280, 'ticker': 'ZTS', 'title': 'Zoetis Inc.'},
 '233': {'cik_str': 1061219,
  'ticker': 'EPD',
  'title': 'ENTERPRISE PRODUCTS PARTNERS L.P.'},
 '234': {'cik_str': 1067491, 'ticker': 'INFY', 'title': 'Infosys Ltd'},
 '235': {'cik_str': 16875,
  'ticker': 'CP',
  'title': 'CANADIAN PACIFIC KANSAS CITY LTD/CN'},
 '236': {'cik_str': 1063761,
  'ticker': 'SPG',
  'title': 'SIMON PROPERTY GROUP INC /DE/'},
 '237': {'cik_str': 1017413,
  'ticker': 'CNQ',
  'title': 'CANADIAN NATURAL RESOURCES LTD'},
 '238': {'cik_str': 702165, 'ticker': 'NSC', 'title': 'NORFOLK SOUTHERN CORP'},
 '239': {'cik_str': 277948, 'ticker': 'CSX', 'title': 'CSX CORP'},
 '240': {'cik_str': 1633917,
  'ticker': 'PYPL',
  'title': 'PayPal Holdings, Inc.'},
 '241': {'cik_str': 1160106,
  'ticker': 'LYG',
  'title': 'Lloyds Banking Group plc'},
 '242': {'cik_str': 865752,
  'ticker': 'MNST',
  'title': 'Monster Beverage Corp'},
 '243': {'cik_str': 21665, 'ticker': 'CL', 'title': 'COLGATE PALMOLIVE CO'},
 '244': {'cik_str': 1262039, 'ticker': 'FTNT', 'title': 'Fortinet, Inc.'},
 '245': {'cik_str': 1129137,
  'ticker': 'AMX',
  'title': 'AMERICA MOVIL SAB DE CV/'},
 '246': {'cik_str': 1506307, 'ticker': 'KMI', 'title': 'KINDER MORGAN, INC.'},
 '247': {'cik_str': 1692819, 'ticker': 'VST', 'title': 'Vistra Corp.'},
 '248': {'cik_str': 1140625, 'ticker': 'EQNR', 'title': 'EQUINOR ASA'},
 '249': {'cik_str': 1588489,
  'ticker': 'GBTC',
  'title': 'Grayscale Bitcoin Trust ETF'},
 '250': {'cik_str': 821189, 'ticker': 'EOG', 'title': 'EOG RESOURCES INC'},
 '251': {'cik_str': 1585689,
  'ticker': 'HLT',
  'title': 'Hilton Worldwide Holdings Inc.'},
 '252': {'cik_str': 1067701, 'ticker': 'URI', 'title': 'UNITED RENTALS, INC.'},
 '253': {'cik_str': 86312,
  'ticker': 'TRV',

In [8]:
ticker_to_cik_map = {info['ticker']: str(info['cik_str']).zfill(10) for info in response.json().values()}

In [9]:
ticker_to_cik_map["CTRA"]

'0000858470'

In [10]:
def get_sec_facts(cik):
    url = f"https://data.sec.gov/api/xbrl/companyfacts/CIK{cik}.json"
    headers = {'User-Agent': 'YourAppName/1.0 (your.email@example.com)'}  # Replace with your details
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        return response.json()
    else:
        raise Exception(f"Failed to fetch data: {response.status_code}")

In [13]:
facts = get_sec_facts(ticker_to_cik_map["CTRA"])

In [20]:
"us-gaap" in facts["facts"]

True

In [30]:
import pandas as pd

def extract_quarterly_data(facts: dict, metric_name: str, unit: str) -> pd.DataFrame:
       
    if "us-gaap" not in facts:
        return pd.DataFrame()
    
    if metric_name not in facts["us-gaap"]:
        return pd.DataFrame()
    
    if unit not in facts["us-gaap"][metric_name]["units"]:
        return pd.DataFrame()
    
    data = facts["us-gaap"][metric_name]["units"][unit]
    df = pd.DataFrame(data)
    df['end'] = pd.to_datetime(df['end'])
    df = df.sort_values(by='end').reset_index(drop=True)
    
    return df

In [31]:
facts["facts"]["us-gaap"]["EarningsPerShareBasic"]["units"]["USD/shares"]

[{'start': '2007-01-01',
  'end': '2007-12-31',
  'val': 1.73,
  'accn': '0001193125-10-042257',
  'fy': 2009,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-02-26',
  'frame': 'CY2007'},
 {'start': '2008-01-01',
  'end': '2008-06-30',
  'val': 1.03,
  'accn': '0001193125-09-159490',
  'fy': 2009,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2009-07-30'},
 {'start': '2008-04-01',
  'end': '2008-06-30',
  'val': 0.55,
  'accn': '0001193125-09-159490',
  'fy': 2009,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2009-07-30',
  'frame': 'CY2008Q2'},
 {'start': '2008-01-01',
  'end': '2008-09-30',
  'val': 1.68,
  'accn': '0001193125-09-217450',
  'fy': 2009,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2009-10-29'},
 {'start': '2008-07-01',
  'end': '2008-09-30',
  'val': 0.65,
  'accn': '0001193125-09-217450',
  'fy': 2009,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2009-10-29',
  'frame': 'CY2008Q3'},
 {'start': '2008-01-01',
  'end': '2008-12-31',
  'val': 2.1,
  'accn': '0001193125-10-042257',
  'fy': 2009,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-02-26'},
 {'start': '2008-01-01',
  'end': '2008-12-31',
  'val': 2.1,
  'accn': '0001193125-11-049690',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2011-02-28',
  'frame': 'CY2008'},
 {'start': '2009-01-01',
  'end': '2009-03-31',
  'val': 0.46,
  'accn': '0001193125-10-100927',
  'fy': 2010,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2010-04-30',
  'frame': 'CY2009Q1'},
 {'start': '2009-01-01',
  'end': '2009-06-30',
  'val': 0.71,
  'accn': '0001193125-09-159490',
  'fy': 2009,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2009-07-30'},
 {'start': '2009-01-01',
  'end': '2009-06-30',
  'val': 0.71,
  'accn': '0001193125-10-171983',
  'fy': 2010,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2010-07-30'},
 {'start': '2009-04-01',
  'end': '2009-06-30',
  'val': 0.25,
  'accn': '0001193125-09-159490',
  'fy': 2009,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2009-07-30'},
 {'start': '2009-04-01',
  'end': '2009-06-30',
  'val': 0.25,
  'accn': '0001193125-10-171983',
  'fy': 2010,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2010-07-30',
  'frame': 'CY2009Q2'},
 {'start': '2009-01-01',
  'end': '2009-09-30',
  'val': 1.08,
  'accn': '0001193125-09-217450',
  'fy': 2009,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2009-10-29'},
 {'start': '2009-07-01',
  'end': '2009-09-30',
  'val': 0.38,
  'accn': '0001193125-09-217450',
  'fy': 2009,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2009-10-29',
  'frame': 'CY2009Q3'},
 {'start': '2009-01-01',
  'end': '2009-12-31',
  'val': 1.43,
  'accn': '0001193125-10-042257',
  'fy': 2009,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2010-02-26'},
 {'start': '2009-01-01',
  'end': '2009-12-31',
  'val': 1.43,
  'accn': '0001193125-11-049690',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2011-02-28'},
 {'start': '2009-01-01',
  'end': '2009-12-31',
  'val': 0.72,
  'accn': '0001047469-12-001751',
  'fy': 2011,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2012-02-28',
  'frame': 'CY2009'},
 {'start': '2010-01-01',
  'end': '2010-03-31',
  'val': 0.28,
  'accn': '0001193125-10-100927',
  'fy': 2010,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2010-04-30'},
 {'start': '2010-01-01',
  'end': '2010-03-31',
  'val': 0.28,
  'accn': '0001193125-11-117544',
  'fy': 2011,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2011-04-29',
  'frame': 'CY2010Q1'},
 {'start': '2010-01-01',
  'end': '2010-06-30',
  'val': 0.49,
  'accn': '0001193125-10-171983',
  'fy': 2010,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2010-07-30'},
 {'start': '2010-01-01',
  'end': '2010-06-30',
  'val': 0.49,
  'accn': '0001193125-11-202290',
  'fy': 2011,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2011-07-29'},
 {'start': '2010-04-01',
  'end': '2010-06-30',
  'val': 0.21,
  'accn': '0001193125-10-171983',
  'fy': 2010,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2010-07-30'},
 {'start': '2010-04-01',
  'end': '2010-06-30',
  'val': 0.21,
  'accn': '0001193125-11-202290',
  'fy': 2011,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2011-07-29',
  'frame': 'CY2010Q2'},
 {'start': '2010-01-01',
  'end': '2010-09-30',
  'val': 0.52,
  'accn': '0001104659-11-058807',
  'fy': 2011,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2011-10-28'},
 {'start': '2010-07-01',
  'end': '2010-09-30',
  'val': 0.04,
  'accn': '0001104659-11-058807',
  'fy': 2011,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2011-10-28',
  'frame': 'CY2010Q3'},
 {'start': '2010-01-01',
  'end': '2010-12-31',
  'val': 0.99,
  'accn': '0001193125-11-049690',
  'fy': 2010,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2011-02-28'},
 {'start': '2010-01-01',
  'end': '2010-12-31',
  'val': 0.5,
  'accn': '0001047469-12-001751',
  'fy': 2011,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2012-02-28'},
 {'start': '2010-01-01',
  'end': '2010-12-31',
  'val': 0.5,
  'accn': '0001047469-13-001948',
  'fy': 2012,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2013-02-28',
  'frame': 'CY2010'},
 {'start': '2011-01-01',
  'end': '2011-03-31',
  'val': 0.12,
  'accn': '0001193125-11-117544',
  'fy': 2011,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2011-04-29'},
 {'start': '2011-01-01',
  'end': '2011-03-31',
  'val': 0.06,
  'accn': '0001104659-12-029890',
  'fy': 2012,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2012-04-27',
  'frame': 'CY2011Q1'},
 {'start': '2011-01-01',
  'end': '2011-06-30',
  'val': 0.65,
  'accn': '0001193125-11-202290',
  'fy': 2011,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2011-07-29'},
 {'start': '2011-01-01',
  'end': '2011-06-30',
  'val': 0.32,
  'accn': '0001104659-12-051649',
  'fy': 2012,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2012-07-27'},
 {'start': '2011-04-01',
  'end': '2011-06-30',
  'val': 0.53,
  'accn': '0001193125-11-202290',
  'fy': 2011,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2011-07-29'},
 {'start': '2011-04-01',
  'end': '2011-06-30',
  'val': 0.26,
  'accn': '0001104659-12-051649',
  'fy': 2012,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2012-07-27',
  'frame': 'CY2011Q2'},
 {'start': '2011-01-01',
  'end': '2011-09-30',
  'val': 0.92,
  'accn': '0001104659-11-058807',
  'fy': 2011,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2011-10-28'},
 {'start': '2011-01-01',
  'end': '2011-09-30',
  'val': 0.46,
  'accn': '0001104659-12-071549',
  'fy': 2012,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2012-10-26'},
 {'start': '2011-07-01',
  'end': '2011-09-30',
  'val': 0.27,
  'accn': '0001104659-11-058807',
  'fy': 2011,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2011-10-28'},
 {'start': '2011-07-01',
  'end': '2011-09-30',
  'val': 0.14,
  'accn': '0001104659-12-071549',
  'fy': 2012,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2012-10-26',
  'frame': 'CY2011Q3'},
 {'start': '2011-01-01',
  'end': '2011-12-31',
  'val': 0.59,
  'accn': '0001047469-12-001751',
  'fy': 2011,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2012-02-28'},
 {'start': '2011-01-01',
  'end': '2011-12-31',
  'val': 0.59,
  'accn': '0001047469-13-001948',
  'fy': 2012,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2013-02-28'},
 {'start': '2011-01-01',
  'end': '2011-12-31',
  'val': 0.29,
  'accn': '0001047469-14-001538',
  'fy': 2013,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2014-02-28',
  'frame': 'CY2011'},
 {'start': '2012-01-01',
  'end': '2012-03-31',
  'val': 0.09,
  'accn': '0001104659-12-029890',
  'fy': 2012,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2012-04-27'},
 {'start': '2012-01-01',
  'end': '2012-03-31',
  'val': 0.09,
  'accn': '0001104659-13-033398',
  'fy': 2013,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2013-04-26',
  'frame': 'CY2012Q1'},
 {'start': '2012-01-01',
  'end': '2012-06-30',
  'val': 0.26,
  'accn': '0001104659-12-051649',
  'fy': 2012,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2012-07-27'},
 {'start': '2012-01-01',
  'end': '2012-06-30',
  'val': 0.26,
  'accn': '0001104659-13-056880',
  'fy': 2013,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2013-07-26'},
 {'start': '2012-04-01',
  'end': '2012-06-30',
  'val': 0.17,
  'accn': '0001104659-12-051649',
  'fy': 2012,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2012-07-27'},
 {'start': '2012-04-01',
  'end': '2012-06-30',
  'val': 0.17,
  'accn': '0001104659-13-056880',
  'fy': 2013,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2013-07-26',
  'frame': 'CY2012Q2'},
 {'start': '2012-01-01',
  'end': '2012-09-30',
  'val': 0.43,
  'accn': '0001104659-12-071549',
  'fy': 2012,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2012-10-26'},
 {'start': '2012-01-01',
  'end': '2012-09-30',
  'val': 0.22,
  'accn': '0001104659-13-077893',
  'fy': 2013,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2013-10-25'},
 {'start': '2012-07-01',
  'end': '2012-09-30',
  'val': 0.17,
  'accn': '0001104659-12-071549',
  'fy': 2012,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2012-10-26'},
 {'start': '2012-07-01',
  'end': '2012-09-30',
  'val': 0.09,
  'accn': '0001104659-13-077893',
  'fy': 2013,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2013-10-25',
  'frame': 'CY2012Q3'},
 {'start': '2012-01-01',
  'end': '2012-12-31',
  'val': 0.63,
  'accn': '0001047469-13-001948',
  'fy': 2012,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2013-02-28'},
 {'start': '2012-01-01',
  'end': '2012-12-31',
  'val': 0.31,
  'accn': '0001047469-14-001538',
  'fy': 2013,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2014-02-28'},
 {'start': '2012-01-01',
  'end': '2012-12-31',
  'val': 0.31,
  'accn': '0001628280-15-001120',
  'fy': 2014,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2015-02-27',
  'frame': 'CY2012'},
 {'start': '2013-01-01',
  'end': '2013-03-31',
  'val': 0.2,
  'accn': '0001104659-13-033398',
  'fy': 2013,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2013-04-26'},
 {'start': '2013-01-01',
  'end': '2013-03-31',
  'val': 0.1,
  'accn': '0001104659-14-030311',
  'fy': 2014,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2014-04-25',
  'frame': 'CY2013Q1'},
 {'start': '2013-01-01',
  'end': '2013-06-30',
  'val': 0.63,
  'accn': '0001104659-13-056880',
  'fy': 2013,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2013-07-26'},
 {'start': '2013-01-01',
  'end': '2013-06-30',
  'val': 0.32,
  'accn': '0001104659-14-053505',
  'fy': 2014,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2014-07-25'},
 {'start': '2013-04-01',
  'end': '2013-06-30',
  'val': 0.42,
  'accn': '0001104659-13-056880',
  'fy': 2013,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2013-07-26'},
 {'start': '2013-04-01',
  'end': '2013-06-30',
  'val': 0.21,
  'accn': '0001104659-14-053505',
  'fy': 2014,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2014-07-25',
  'frame': 'CY2013Q2'},
 {'start': '2013-01-01',
  'end': '2013-09-30',
  'val': 0.48,
  'accn': '0001104659-13-077893',
  'fy': 2013,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2013-10-25'},
 {'start': '2013-01-01',
  'end': '2013-09-30',
  'val': 0.48,
  'accn': '0001445305-14-004439',
  'fy': 2014,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2014-10-24'},
 {'start': '2013-07-01',
  'end': '2013-09-30',
  'val': 0.17,
  'accn': '0001104659-13-077893',
  'fy': 2013,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2013-10-25'},
 {'start': '2013-07-01',
  'end': '2013-09-30',
  'val': 0.17,
  'accn': '0001445305-14-004439',
  'fy': 2014,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2014-10-24',
  'frame': 'CY2013Q3'},
 {'start': '2013-01-01',
  'end': '2013-12-31',
  'val': 0.67,
  'accn': '0001047469-14-001538',
  'fy': 2013,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2014-02-28'},
 {'start': '2013-01-01',
  'end': '2013-12-31',
  'val': 0.67,
  'accn': '0001628280-15-001120',
  'fy': 2014,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2015-02-27'},
 {'start': '2013-01-01',
  'end': '2013-12-31',
  'val': 0.67,
  'accn': '0000858470-16-000036',
  'fy': 2015,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2016-02-22',
  'frame': 'CY2013'},
 {'start': '2014-01-01',
  'end': '2014-03-31',
  'val': 0.26,
  'accn': '0001104659-14-030311',
  'fy': 2014,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2014-04-25'},
 {'start': '2014-01-01',
  'end': '2014-03-31',
  'val': 0.26,
  'accn': '0000858470-15-000006',
  'fy': 2015,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2015-04-24',
  'frame': 'CY2014Q1'},
 {'start': '2014-01-01',
  'end': '2014-06-30',
  'val': 0.54,
  'accn': '0001104659-14-053505',
  'fy': 2014,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2014-07-25'},
 {'start': '2014-01-01',
  'end': '2014-06-30',
  'val': 0.54,
  'accn': '0000858470-15-000015',
  'fy': 2015,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2015-07-24'},
 {'start': '2014-04-01',
  'end': '2014-06-30',
  'val': 0.28,
  'accn': '0001104659-14-053505',
  'fy': 2014,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2014-07-25'},
 {'start': '2014-04-01',
  'end': '2014-06-30',
  'val': 0.28,
  'accn': '0000858470-15-000015',
  'fy': 2015,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2015-07-24',
  'frame': 'CY2014Q2'},
 {'start': '2014-01-01',
  'end': '2014-09-30',
  'val': 0.78,
  'accn': '0001445305-14-004439',
  'fy': 2014,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2014-10-24'},
 {'start': '2014-01-01',
  'end': '2014-09-30',
  'val': 0.78,
  'accn': '0000858470-15-000027',
  'fy': 2015,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2015-10-23'},
 {'start': '2014-07-01',
  'end': '2014-09-30',
  'val': 0.24,
  'accn': '0001445305-14-004439',
  'fy': 2014,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2014-10-24'},
 {'start': '2014-07-01',
  'end': '2014-09-30',
  'val': 0.24,
  'accn': '0000858470-15-000027',
  'fy': 2015,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2015-10-23',
  'frame': 'CY2014Q3'},
 {'start': '2014-01-01',
  'end': '2014-12-31',
  'val': 0.25,
  'accn': '0001628280-15-001120',
  'fy': 2014,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2015-02-27'},
 {'start': '2014-01-01',
  'end': '2014-12-31',
  'val': 0.25,
  'accn': '0000858470-16-000036',
  'fy': 2015,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2016-02-22'},
 {'start': '2014-01-01',
  'end': '2014-12-31',
  'val': 0.25,
  'accn': '0000858470-17-000007',
  'fy': 2016,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2017-02-27',
  'frame': 'CY2014'},
 {'start': '2015-01-01',
  'end': '2015-03-31',
  'val': 0.1,
  'accn': '0000858470-15-000006',
  'fy': 2015,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2015-04-24'},
 {'start': '2015-01-01',
  'end': '2015-03-31',
  'val': 0.1,
  'accn': '0000858470-16-000049',
  'fy': 2016,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2016-05-03',
  'frame': 'CY2015Q1'},
 {'start': '2015-01-01',
  'end': '2015-06-30',
  'val': 0.03,
  'accn': '0000858470-15-000015',
  'fy': 2015,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2015-07-24'},
 {'start': '2015-01-01',
  'end': '2015-06-30',
  'val': 0.03,
  'accn': '0000858470-16-000061',
  'fy': 2016,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2016-07-29'},
 {'start': '2015-04-01',
  'end': '2015-06-30',
  'val': -0.07,
  'accn': '0000858470-15-000015',
  'fy': 2015,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2015-07-24'},
 {'start': '2015-04-01',
  'end': '2015-06-30',
  'val': -0.07,
  'accn': '0000858470-16-000061',
  'fy': 2016,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2016-07-29',
  'frame': 'CY2015Q2'},
 {'start': '2015-01-01',
  'end': '2015-09-30',
  'val': -0.01,
  'accn': '0000858470-15-000027',
  'fy': 2015,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2015-10-23'},
 {'start': '2015-01-01',
  'end': '2015-09-30',
  'val': -0.01,
  'accn': '0000858470-16-000066',
  'fy': 2016,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2016-10-28'},
 {'start': '2015-07-01',
  'end': '2015-09-30',
  'val': -0.04,
  'accn': '0000858470-15-000027',
  'fy': 2015,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2015-10-23'},
 {'start': '2015-07-01',
  'end': '2015-09-30',
  'val': -0.04,
  'accn': '0000858470-16-000066',
  'fy': 2016,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2016-10-28',
  'frame': 'CY2015Q3'},
 {'start': '2015-01-01',
  'end': '2015-12-31',
  'val': -0.28,
  'accn': '0000858470-16-000036',
  'fy': 2015,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2016-02-22'},
 {'start': '2015-01-01',
  'end': '2015-12-31',
  'val': -0.28,
  'accn': '0000858470-17-000007',
  'fy': 2016,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2017-02-27'},
 {'start': '2015-01-01',
  'end': '2015-12-31',
  'val': -0.28,
  'accn': '0000858470-18-000006',
  'fy': 2017,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2018-03-01'},
 {'start': '2015-01-01',
  'end': '2015-12-31',
  'val': -0.28,
  'accn': '0000858470-18-000009',
  'fy': 2017,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2018-03-02',
  'frame': 'CY2015'},
 {'start': '2016-01-01',
  'end': '2016-03-31',
  'val': -0.12,
  'accn': '0000858470-16-000049',
  'fy': 2016,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2016-05-03'},
 {'start': '2016-01-01',
  'end': '2016-03-31',
  'val': -0.12,
  'accn': '0000858470-17-000013',
  'fy': 2017,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2017-04-28',
  'frame': 'CY2016Q1'},
 {'start': '2016-01-01',
  'end': '2016-06-30',
  'val': -0.25,
  'accn': '0000858470-16-000061',
  'fy': 2016,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2016-07-29'},
 {'start': '2016-01-01',
  'end': '2016-06-30',
  'val': -0.25,
  'accn': '0000858470-17-000023',
  'fy': 2017,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2017-07-28'},
 {'start': '2016-04-01',
  'end': '2016-06-30',
  'val': -0.14,
  'accn': '0000858470-16-000061',
  'fy': 2016,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2016-07-29'},
 {'start': '2016-04-01',
  'end': '2016-06-30',
  'val': -0.14,
  'accn': '0000858470-17-000023',
  'fy': 2017,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2017-07-28',
  'frame': 'CY2016Q2'},
 {'start': '2016-01-01',
  'end': '2016-09-30',
  'val': -0.27,
  'accn': '0000858470-16-000066',
  'fy': 2016,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2016-10-28'},
 {'start': '2016-01-01',
  'end': '2016-09-30',
  'val': -0.27,
  'accn': '0000858470-17-000024',
  'fy': 2017,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2017-10-30'},
 {'start': '2016-07-01',
  'end': '2016-09-30',
  'val': -0.02,
  'accn': '0000858470-16-000066',
  'fy': 2016,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2016-10-28'},
 {'start': '2016-07-01',
  'end': '2016-09-30',
  'val': -0.02,
  'accn': '0000858470-17-000024',
  'fy': 2017,
  'fp': 'Q3',
  'form': '10-Q',
  'filed': '2017-10-30',
  'frame': 'CY2016Q3'},
 {'start': '2016-01-01',
  'end': '2016-12-31',
  'val': -0.91,
  'accn': '0000858470-17-000007',
  'fy': 2016,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2017-02-27'},
 {'start': '2016-01-01',
  'end': '2016-12-31',
  'val': -0.91,
  'accn': '0000858470-18-000006',
  'fy': 2017,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2018-03-01'},
 {'start': '2016-01-01',
  'end': '2016-12-31',
  'val': -0.91,
  'accn': '0000858470-18-000009',
  'fy': 2017,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2018-03-02'},
 {'start': '2016-01-01',
  'end': '2016-12-31',
  'val': -0.91,
  'accn': '0000858470-19-000008',
  'fy': 2018,
  'fp': 'FY',
  'form': '10-K',
  'filed': '2019-02-26',
  'frame': 'CY2016'},
 {'start': '2017-01-01',
  'end': '2017-03-31',
  'val': 0.23,
  'accn': '0000858470-17-000013',
  'fy': 2017,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2017-04-28'},
 {'start': '2017-01-01',
  'end': '2017-03-31',
  'val': 0.23,
  'accn': '0000858470-18-000022',
  'fy': 2018,
  'fp': 'Q1',
  'form': '10-Q',
  'filed': '2018-04-27',
  'frame': 'CY2017Q1'},
 {'start': '2017-01-01',
  'end': '2017-06-30',
  'val': 0.27,
  'accn': '0000858470-17-000023',
  'fy': 2017,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2017-07-28'},
 {'start': '2017-01-01',
  'end': '2017-06-30',
  'val': 0.27,
  'accn': '0000858470-18-000043',
  'fy': 2018,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2018-07-27'},
 {'start': '2017-04-01',
  'end': '2017-06-30',
  'val': 0.05,
  'accn': '0000858470-17-000023',
  'fy': 2017,
  'fp': 'Q2',
  'form': '10-Q',
  'filed': '2017-07-28'},
 {'start': '2017-04-01',
  'end': '2017-06-30',

In [36]:
x = extract_quarterly_data(facts["facts"], 'EarningsPerShareBasic', 'USD/shares')

In [40]:
x["end"] = pd.to_datetime(x["end"])
x["start"] = pd.to_datetime(x["start"])

In [42]:
x.groupby("end")["start"].idxmax()

end
2007-12-31      0
2008-06-30      2
2008-09-30      4
2008-12-31      5
2009-03-31      7
             ...
2024-09-30    215
2024-12-31    217
2025-03-31    218
2025-06-30    220
2025-09-30    222
Name: start, Length: 71, dtype: int64

In [50]:
equity_table = extract_quarterly_data(facts["facts"], 'StockholdersEquity', 'USD')
shares_table = extract_quarterly_data(facts["facts"], 'CommonStockSharesIssued', 'shares')

In [54]:
bv_df = pd.merge(equity_table, shares_table, on=["end","fy", "fp"], suffixes=("_equity", "_shares"))

In [55]:
bv_df

,end,val_equity,accn_equity,fy,fp,form_equity,filed_equity,frame_equity,val_shares,accn_shares,form_shares,filed_shares,frame_shares
0,2008-12-31,1790562000,0001193125-09-159490,2009,Q2,10-Q,2009-07-30,NaN,103561268,0001193125-09-159490,10-Q,2009-07-30,NaN
1,2008-12-31,1790562000,0001193125-09-217450,2009,Q3,10-Q,2009-10-29,NaN,103561268,0001193125-09-217450,10-Q,2009-10-29,NaN
2,2008-12-31,1790562000,0001193125-10-042257,2009,FY,10-K,2010-02-26,NaN,103561268,0001193125-10-042257,10-K,2010-02-26,CY2008Q4I
3,2009-06-30,1836472000,0001193125-09-159490,2009,Q2,10-Q,2009-07-30,CY2009Q2I,103846636,0001193125-09-159490,10-Q,2009-07-30,CY2009Q2I
4,2009-09-30,1823814000,0001193125-09-217450,2009,Q3,10-Q,2009-10-29,CY2009Q3I,103856313,0001193125-09-217450,10-Q,2009-10-29,CY2009Q3I
...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,2024-12-31,13122000000,0000858470-25-000165,2025,Q2,10-Q,2025-08-05,NaN,735000000,0000858470-25-000165,10-Q,2025-08-05,NaN
134,2024-12-31,13122000000,0000858470-25-000199,2025,Q3,10-Q,2025-11-04,CY2024Q4I,735000000,0000858470-25-000199,10-Q,2025-11-04,CY2024Q4I
135,2025-03-31,14224000000,0000858470-25-000111,2025,Q1,10-Q,2025-05-06,NaN,764000000,0000858470-25-000111,10-Q,2025-05-06,CY2025Q1I
136,2025-06-30,14556000000,0000858470-25-000165,2025,Q2,10-Q,2025-08-05,NaN,763000000,0000858470-25-000165,10-Q,2025-08-05,CY2025Q2I
137,2025-09-30,14718000000,0000858470-25-000199,2025,Q3,10-Q,2025-11-04,CY2025Q3I,764000000,0000858470-25-000199,10-Q,2025-11-04,CY2025Q3I